name: Pull Request Check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/client/node_modules
            **/api/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: Lint Client
        if: always()
        run: |
          cd client
          yarn client-lint

      - name: Lint API
        if: always()
        run: |
          cd api
          yarn api-lint
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/client/node_modules
            **/api/node_modules
            ${{ github.workspace }}/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: Build Client
        if: always()
        run: |
          cd client
          yarn client-build


