name: Pull Request Check

# Runs on PR to master and develop but also for direct commits to master in develop as they shouldn't be skipped
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install

      - name: Lint Client
        if: always()
        run: |
          cd client
          yarn client-lint

      - name: Lint API
        if: always()
        run: |
          cd api
          yarn api-lint
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles(${{ github.workspace }}/yarn.lock) }}
      - run: yarn install

      - name: Build Client
        if: always()
        run: |
          cd client
          yarn client-build


